repos:
  - repo: https://github.com/psf/black
    rev: 24.10.0  # Use the latest stable version
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0  # Match your mypy version
    hooks:
      - id: mypy
        args: [--install-types, --non-interactive, --cache-dir=.mypy_cache/]  # Ensure types are installed automatically
        additional_dependencies:
        - "pydantic>=2.10.2"

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1  # Use the latest stable version
    hooks:
      - id: flake8

  - repo:  https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0  # Use the latest stable version
    hooks:
      - id: check-added-large-files  # Detect large files in commits
      - id: check-merge-conflict  # Check for unresolved merge conflicts
      - id: end-of-file-fixer  # Ensure files end with a newline
      - id: trailing-whitespace  # Remove trailing whitespace
      - id: debug-statements  # Prevent debug statements (e.g., print)
